# Generated by Django 5.1.1 on 2025-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0005_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="22fwiU2fwhdQ9k2o8bGG5RHdJ3dkOQ85",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
